server:
  port: 8091
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    url: jdbc:postgresql://localhost:5432/java5UserDb
    password: 9896
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  queueregister: register-queue
